[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = true

[browser]
serveToAll = true

[runner]
fastReruns = true

[global]
developmentMode = false

[logger]
level = "warning"

[client]
toolbarMode = "minimal"

[deploy]
packageManager = "pip"
requirementsFile = "requirements-streamlit.txt"
